// The ONE template every body pack is written from — Earth included. A pack is
// a single ES module exporting one body object and importing nothing, so it
// can be served from any static host or CDN path without an import map. The
// decoder and the mask sampler are copied in from codec.js by source text, so
// there is exactly one implementation of each to test.

import { ALPHABET, SCALE, decodeRings, maskAt, unpackMask, packPlaces, unpackPlace } from "./codec.js";

// body:     { id, name, radiusKm, latRange, terms: { figure, ground } }
// mask:     { width, height, rle }
// outlines: encoded rings of the figure boundary (string), or null
// borders:  encoded rings of region boundaries (string), or null
// places:   [{ name, lat, lon, kind? }]
export function renderBodyPack({ generatedBy, notes, body, mask, outlines, borders, places, placesNotes }) {
  const exportName = body.id.toUpperCase().replace(/-/g, "_");
  return `// GENERATED by scripts/${generatedBy} — do not edit by hand.
// Places live in scripts/data/${body.id}-places.js; everything else is derived
// from the pinned sources named below. \`npm run generate:${body.id}\` rewrites this file.
//
${comment(notes)}
//
// Format: a ${mask.width}×${mask.height} bitmask (row-major from lat +90 down, lon −180 → +180,
// one bit per cell, stored as run lengths) and closed [lat, lon] rings quantised
// to 1/${SCALE}° and delta+varint encoded — the same encoding every mappo body uses.

export const ${exportName} = (() => {
  const MASK_W = ${mask.width}, MASK_H = ${mask.height};
  const SCALE = ${SCALE};
  const ALPHABET = ${JSON.stringify(ALPHABET)};
  const OUTLINES = ${outlines == null ? "null" : JSON.stringify(outlines)};
  const BORDERS = ${borders == null ? "null" : JSON.stringify(borders)};

${indent(unpackMask.toString(), 2)}

${indent(decodeRings.toString(), 2)}

  const BITS = unpackMask(${JSON.stringify(mask.rle)}, MASK_W, MASK_H, ALPHABET);

${indent(maskAt.toString(), 2)}

${indent(unpackPlace.toString(), 2)}

  let outlines = null, borders = null;

  return {
    id: ${JSON.stringify(body.id)},
    name: ${JSON.stringify(body.name)},
    radiusKm: ${body.radiusKm ?? "null"},
    latRange: [ ${body.latRange[0]}, ${body.latRange[1]} ],
    terms: { figure: ${JSON.stringify(body.terms.figure)}, ground: ${JSON.stringify(body.terms.ground)} },
    figure: (lat, lon) => maskAt(BITS, MASK_W, MASK_H, lat, lon),
    outlines: () => (OUTLINES === null ? null : (outlines ??= decodeRings(OUTLINES, SCALE, ALPHABET))),
    borders: () => (BORDERS === null ? null : (borders ??= decodeRings(BORDERS, SCALE, ALPHABET))),
${comment(placesNotes, 4)}
    places: ${JSON.stringify(packPlaces(places))}.split(";").map(unpackPlace)
  };
})();
`;
}

function comment(text, pad = 0) {
  return String(text ?? "").trim().split("\n").map((line) => `${" ".repeat(pad)}// ${line}`.trimEnd()).join("\n");
}

function indent(source, pad) {
  return source.split("\n").map((line) => (line ? " ".repeat(pad) + line : line)).join("\n");
}

// A body's vector rings as a module of their own, for bodies whose rings are
// too heavy to ride in the core (Earth: a third of the package). Unlike a pack
// it is not standalone — it imports the core to call extendBody() — so the
// build resolves that import to ./mappo.js and every map already drawing the
// body is redrawn with rings the moment the module loads.
export function renderBodyVectorModule({ generatedBy, notes, body, outlines, borders, importFrom = "../body.js" }) {
  return `// GENERATED by scripts/${generatedBy} — do not edit by hand.
// ${body.name}'s vector rings, as an opt-in module: import it and every map of
// ${body.name} gains figure-source="vector" outlines and borders. Derived from
// the pinned sources named below; \`npm run generate:${body.id}\` rewrites this file.
//
${comment(notes)}
//
// Format: closed [lat, lon] rings quantised to 1/${SCALE}° and delta+varint
// encoded — the same encoding every mappo body uses.

import { extendBody } from ${JSON.stringify(importFrom)};

const OUTLINES = ${outlines == null ? "null" : JSON.stringify(outlines)};
const BORDERS = ${borders == null ? "null" : JSON.stringify(borders)};
const SCALE = ${SCALE};
const ALPHABET = ${JSON.stringify(ALPHABET)};

${decodeRings.toString()}

let outlines = null, borders = null;

extendBody(${JSON.stringify(body.id)}, {
  outlines: () => (OUTLINES === null ? null : (outlines ??= decodeRings(OUTLINES, SCALE, ALPHABET))),
  borders: () => (BORDERS === null ? null : (borders ??= decodeRings(BORDERS, SCALE, ALPHABET)))
});
`;
}
