// The ONE template every body pack is written from — Earth included. A pack is
// a single ES module exporting one body object and importing nothing, so it
// can be served from any static host or CDN path without an import map. The
// decoder and the mask sampler are copied in from codec.js by source text, so
// there is exactly one implementation of each to test.

import { ALPHABET, SCALE, decodeRings, maskAt } from "./codec.js";

// body:     { id, name, radiusKm, latRange, terms: { figure, ground } }
// mask:     { width, height, base64 }
// outlines: encoded rings of the figure boundary (string), or null
// borders:  encoded rings of region boundaries (string), or null
// places:   [{ name, lat, lon, kind? }]
export function renderBodyPack({ generatedBy, notes, body, mask, outlines, borders, places, placesNotes }) {
  const exportName = body.id.toUpperCase().replace(/-/g, "_");
  return `// GENERATED by scripts/${generatedBy} — do not edit by hand.
// Places live in scripts/data/${body.id}-places.js; everything else is derived
// from the pinned sources named below. \`npm run generate:${body.id}\` rewrites this file.
//
${comment(notes)}
//
// Format: a ${mask.width}×${mask.height} bitmask (row-major from lat +90 down, lon −180 → +180,
// one bit per cell) and closed [lat, lon] rings quantised to 1/${SCALE}° and
// delta+varint encoded — the same encoding every mappo body uses.

export const ${exportName} = (() => {
  const MASK_W = ${mask.width}, MASK_H = ${mask.height};
  const BITS = Uint8Array.from(atob(${JSON.stringify(mask.base64)}), (c) => c.charCodeAt(0));
  const OUTLINES = ${outlines == null ? "null" : JSON.stringify(outlines)};
  const BORDERS = ${borders == null ? "null" : JSON.stringify(borders)};
  const SCALE = ${SCALE};
  const ALPHABET = ${JSON.stringify(ALPHABET)};

${indent(decodeRings.toString(), 2)}

${indent(maskAt.toString(), 2)}

  let outlines = null, borders = null;

  return {
    id: ${JSON.stringify(body.id)},
    name: ${JSON.stringify(body.name)},
    radiusKm: ${body.radiusKm ?? "null"},
    latRange: [ ${body.latRange[0]}, ${body.latRange[1]} ],
    terms: { figure: ${JSON.stringify(body.terms.figure)}, ground: ${JSON.stringify(body.terms.ground)} },
    figure: (lat, lon) => maskAt(BITS, MASK_W, MASK_H, lat, lon),
    outlines: () => (OUTLINES === null ? null : (outlines ??= decodeRings(OUTLINES, SCALE, ALPHABET))),
    borders: () => (BORDERS === null ? null : (borders ??= decodeRings(BORDERS, SCALE, ALPHABET))),
${comment(placesNotes, 4)}
    places: [
${places.map((p) => `      ${place(p)}`).join(",\n")}
    ]
  };
})();
`;
}

function place({ name, lat, lon, kind }) {
  return `{ name: ${JSON.stringify(name)}, lat: ${lat}, lon: ${lon}${kind ? `, kind: ${JSON.stringify(kind)}` : ""} }`;
}

function comment(text, pad = 0) {
  return String(text ?? "").trim().split("\n").map((line) => `${" ".repeat(pad)}// ${line}`.trimEnd()).join("\n");
}

function indent(source, pad) {
  return source.split("\n").map((line) => (line ? " ".repeat(pad) + line : line)).join("\n");
}
